add notebook for preprocessing input datasets
GeoscienceAustralia/uncover-ml pull request #138
Opened 2021-01-25 03:58 UTC by sheecegardezi

- remove any duplicate datasets in input 
- if a dataset contains more then one band then create a new dataset for each band
- if a dataset in not in EPSG:3577; reproject it in EPSG:3577 projection
- if a user has provided a smaller area of interest then crop the input datasets accordingly
- create a vector csv file from the input datasets
- drop no data values from csv
- Save Normalized Dataset
- - maximum absolute
- - quantile 
- - standard scaler

2021-01-26 23:25 UTC, zhang01GA approved these changes

2021-01-27 00:08 UTC, zhang01GA requested changes
Hi Sheece,

I just noticed that the original notebooks are deleted. I think they should be kept for reference

2021-01-27 22:54 UTC, sheecegardezi commented
> 
> 
> Hi Sheece,
> 
> I just noticed that the original notebooks are deleted. I think they should be kept for reference

These notebooks are no longer maintained. I could not reproduce the results shared in these notebooks.  I'll revert this commit.

2021-01-27 23:13 UTC, RichardScottOZ commented
> Hi Sheece,
> 
> I just noticed that the original notebooks are deleted. I think they should be kept for reference

I would agree with that, even if you put them in an 'older work' folder, etc.  The methodology/approach/ideas can be valuable - and jumpstarts to other work/developers.

2021-02-01 05:47 UTC, merged